export interface CategoryInfo {
  label: string;
  icon: string;
}

export const BROWSE_CATEGORIES: CategoryInfo[] = [
  { label: "Cleaning", icon: "cleaning_services" },
  { label: "Home Repairs", icon: "handyman" },
  { label: "Furniture Assembly", icon: "chair" },
  { label: "Mounting & Installation", icon: "tv" },
  { label: "Moving & Packing", icon: "local_shipping" },
  { label: "Yard Work & Gardening", icon: "yard" },
  { label: "Shopping & Delivery", icon: "shopping_cart" },
  { label: "Personal Assistant", icon: "support_agent" },
  { label: "Organization", icon: "inventory_2" },
  { label: "Holiday Help", icon: "celebration" },
  { label: "Office Services", icon: "business_center" },
  { label: "Virtual & Online", icon: "computer" },
];

export const CATEGORY_SUBCATEGORIES: Record<string, string[]> = {
  Cleaning: [
    "House Cleaning Services",
    "Deep Cleaning",
    "Disinfecting Services",
    "Move In Cleaning",
    "Move Out Cleaning",
    "Vacation Rental Cleaning",
    "Carpet Cleaning Service",
    "Garage Cleaning",
    "One Time Cleaning Services",
    "Car Washing",
    "Laundry Help",
    "Pressure Washing",
    "Spring Cleaning",
  ],

  "Home Repairs": [
    "Home Repairs",
    "Door, Cabinet, & Furniture Repair",
    "Appliance Installation & Repairs",
    "Drywall Repair Service",
    "Flooring & Tiling Help",
    "Electrical Help",
    "Sealing & Caulking",
    "Plumbing",
    "Window & Blinds Repair",
    "Ceiling Fan Installation",
    "Smart Home Installation",
    "Install Air Conditioner",
    "Painting",
    "Install Shelves, Rods & Hooks",
    "Home Maintenance",
    "Install Blinds & Window Treatments",
    "Baby Proofing",
    "Light Installation",
    "Carpentry Services",
    "Hang Art, Mirror & Decor",
    "General Mounting",
    "Cabinet Installation",
    "Wallpapering Service",
    "Fence Installation & Repair Services",
    "Deck Restoration Services",
    "Doorbell Installation",
    "Home Theater Installing",
  ],

  "Furniture Assembly": [
    "Furniture Assembly",
    "Patio Furniture Assembly",
    "Desk Assembly",
    "Dresser Assembly",
    "Bed Assembly",
    "Bookshelf Assembly",
    "Couch Assembly",
    "Chair Assembly",
    "Wardrobe Assembly",
    "Table Assembly",
    "Disassemble Furniture",
    "Toy Assembly Service",
  ],

  "Mounting & Installation": [
    "TV Mounting",
    "Install Shelves, Rods & Hooks",
    "Ceiling Fan Installation",
    "Install Blinds & Window Treatments",
    "Hang Art, Mirror & Decor",
    "General Mounting",
    "Hang Christmas Lights",
    "Light Installation",
    "Smart Home Installation",
    "Doorbell Installation",
    "Home Theater Installing",
    "Install Air Conditioner",
  ],

  "Moving & Packing": [
    "Help Moving",
    "Truck Assisted Help Moving",
    "Packing Services & Help",
    "Unpacking Services",
    "Heavy Lifting",
    "Local Movers",
    "Junk Pickup",
    "Furniture Movers",
    "One Item Movers",
    "Storage Unit Moving",
    "Couch Removal",
    "Mattress Pick-Up & Removal",
    "Furniture Removal",
    "Pool Table Movers",
    "Appliance Removal",
    "Heavy Furniture Moving",
    "Rearranging Furniture",
    "Full Service Help Moving",
    "In-Home Furniture Movers",
  ],

  "Yard Work & Gardening": [
    "Gardening Services",
    "Weed Removal",
    "Lawn Care Services",
    "Lawn Mowing Services",
    "Landscaping Services",
    "Gutter Cleaning",
    "Tree Trimming Service",
    "Vacation Plant Watering",
    "Patio Cleaning",
    "Hot Tub Cleaning",
    "Fence Installation & Repair Services",
    "Deck Restoration Services",
    "Patio Furniture Assembly",
    "Fence Staining",
    "Mulching Services",
    "Lawn Fertilizer Service",
    "Hedge Trimming Service",
    "Outdoor Party Setup",
    "Urban Gardening Service",
    "Leaf Raking & Removal",
    "Produce Gardening",
    "Hose Installation",
    "Shed Maintenance",
    "Pressure Washing",
  ],

  "Shopping & Delivery": [
    "Delivery Service",
    "Grocery Shopping & Delivery",
    "Running Your Errands",
    "Christmas Tree Delivery",
    "Wait in Line",
    "Deliver Big Piece of Furniture",
    "Drop Off Donations",
    "Contactless Delivery",
    "Pet Food Delivery",
    "Baby Food Delivery",
    "Return Items",
    "Wait for Delivery",
    "Shipping",
    "Breakfast Delivery",
    "Coffee Delivery",
  ],

  "Personal Assistant": [
    "Personal Assistant",
    "Running Your Errands",
    "Wait in Line",
    "Organization",
    "Organize Home",
    "Closet Organization Service",
    "Interior Design Service",
    "Virtual Assistant",
  ],

  Organization: [
    "Organization",
    "Organize Home",
    "Closet Organization Service",
    "Interior Design Service",
    "Organize a Room",
  ],

  "Holiday Help": [
    "Gift Wrapping Services",
    "Hang Christmas Lights",
    "Christmas Tree Delivery",
    "Holiday Decorating",
    "Party Cleaning",
    "Toy Assembly Service",
    "Wait in Line",
    "Christmas Tree Removal",
  ],

  "Office Services": [
    "Office Cleaning",
    "Office Tech Setup",
    "Office Movers",
    "Office Supply & Snack Delivery",
    "Office Furniture Assembly",
    "Office Setup & Organization",
    "Office Administration",
    "Office Interior Design",
    "Moving Office Furniture",
    "Office Mounting Service",
  ],

  "Virtual & Online": [
    "Virtual Assistant",
    "Organization",
    "Data Entry",
    "Computer Help",
  ],
};

export const SUBCATEGORY_ICONS: Record<string, string> = {
  "House Cleaning Services": "cleaning_services",
  "Deep Cleaning": "cleaning_services",
  "Disinfecting Services": "water_drop",
  "Move In Cleaning": "home_work",
  "Move Out Cleaning": "home_work",
  "Vacation Rental Cleaning": "villa",
  "Carpet Cleaning Service": "cleaning_services",
  "Garage Cleaning": "garage_hospital",
  "One Time Cleaning Services": "cleaning_services",
  "Car Washing": "local_car_wash",
  "Laundry Help": "laundry",
  "Pressure Washing": "water_drop",
  "Spring Cleaning": "cleaning_services",
  "General Cleaning": "cleaning_services",
  "Home Repairs": "handyman",
  "Door, Cabinet, & Furniture Repair": "door_sliding",
  "Appliance Installation & Repairs": "kitchen",
  "Drywall Repair Service": "format_paint",
  "Flooring & Tiling Help": "square_foot",
  "Electrical Help": "electrical_services",
  "Sealing & Caulking": "format_paint",
  "Plumbing": "plumbing",
  "Window & Blinds Repair": "window",
  "Ceiling Fan Installation": "air",
  "Smart Home Installation": "smart_button",
  "Install Air Conditioner": "ac_unit",
  "Painting": "brush",
  "Install Shelves, Rods & Hooks": "inventory_2",
  "Home Maintenance": "home_repair_service",
  "Install Blinds & Window Treatments": "window",
  "Baby Proofing": "child_friendly",
  "Light Installation": "light",
  "Carpentry Services": "carpenter",
  "Hang Art, Mirror & Decor": "photo_frame",
  "General Mounting": "push_pin",
  "Cabinet Installation": "kitchen",
  "Wallpapering Service": "wallpaper",
  "Fence Installation & Repair Services": "fence",
  "Deck Restoration Services": "deck",
  "Doorbell Installation": "doorbell",
  "Home Theater Installing": "surround_sound",
  "Furniture Assembly": "chair",
  "Patio Furniture Assembly": "chair",
  "Desk Assembly": "desk",
  "Dresser Assembly": "table_restaurant",
  "Bed Assembly": "bed",
  "Bookshelf Assembly": "menu_book",
  "Couch Assembly": "weekend",
  "Chair Assembly": "chair",
  "Wardrobe Assembly": "door_sliding",
  "Table Assembly": "table_restaurant",
  "Disassemble Furniture": "handyman",
  "Toy Assembly Service": "toys",
  "TV Mounting": "tv",
  "Hang Christmas Lights": "celebration",
  "Help Moving": "local_shipping",
  "Truck Assisted Help Moving": "truck",
  "Packing Services & Help": "inventory_2",
  "Unpacking Services": "remove_red_eye",
  "Heavy Lifting": "fitness_center",
  "Local Movers": "local_shipping",
  "Junk Pickup": "delete",
  "Furniture Movers": "chair",
  "One Item Movers": "local_shipping",
  "Storage Unit Moving": "warehouse",
  "Couch Removal": "weekend",
  "Mattress Pick-Up & Removal": "bed",
  "Furniture Removal": "chair",
  "Pool Table Movers": "sports_tennis",
  "Appliance Removal": "kitchen",
  "Heavy Furniture Moving": "fitness_center",
  "Rearranging Furniture": "chair",
  "Full Service Help Moving": "local_shipping",
  "In-Home Furniture Movers": "chair",
  "Gardening Services": "yard",
  "Weed Removal": "yard",
  "Lawn Care Services": "yard",
  "Lawn Mowing Services": "yard",
  "Landscaping Services": "yard",
  "Gutter Cleaning": "yard",
  "Tree Trimming Service": "park",
  "Vacation Plant Watering": "yard",
  "Patio Cleaning": "yard",
  "Hot Tub Cleaning": "hot_tub",
  "Fence Staining": "fence",
  "Mulching Services": "yard",
  "Lawn Fertilizer Service": "yard",
  "Hedge Trimming Service": "content_cut",
  "Outdoor Party Setup": "celebration",
  "Urban Gardening Service": "yard",
  "Leaf Raking & Removal": "yard",
  "Produce Gardening": "yard",
  "Hose Installation": "yard",
  "Shed Maintenance": "shed",
  "Delivery Service": "local_shipping",
  "Grocery Shopping & Delivery": "shopping_cart",
  "Running Your Errands": "list_alt",
  "Christmas Tree Delivery": "park",
  "Wait in Line": "schedule",
  "Deliver Big Piece of Furniture": "local_shipping",
  "Drop Off Donations": "volunteer",
  "Contactless Delivery": "local_shipping",
  "Pet Food Delivery": "pets",
  "Baby Food Delivery": "baby_face",
  "Return Items": "assignment_return",
  "Wait for Delivery": "schedule",
  "Shipping": "local_shipping",
  "Breakfast Delivery": "bakery_dining",
  "Coffee Delivery": "coffee",
  "Personal Assistant": "support_agent",
  "Closet Organization Service": "inventory_2",
  "Interior Design Service": "chair",
  "Virtual Assistant": "support_agent",
  "Organize Home": "inventory_2",
  "Organize a Room": "inventory_2",
  "Gift Wrapping Services": "redeem",
  "Holiday Decorating": "celebration",
  "Party Cleaning": "cleaning_services",
  "Christmas Tree Removal": "park",
  "Office Cleaning": "cleaning_services",
  "Office Tech Setup": "computer",
  "Office Movers": "local_shipping",
  "Office Supply & Snack Delivery": "local_shipping",
  "Office Furniture Assembly": "chair",
  "Office Setup & Organization": "inventory_2",
  "Office Administration": "desk",
  "Office Interior Design": "chair",
  "Moving Office Furniture": "move_up",
  "Office Mounting Service": "push_pin",
  "Data Entry": "keyboard",
  "Computer Help": "computer",
};
